### ISSUE TITLE
Тип ошибки

### ISSUE THREAD

**Issue by pecourses** [Maksym04/js.class-syntax#1]
https://github.com/Maksym04/js.class-syntax/blob/4ef3add8aab72c937906913c875dc3b830333069/js/index.js#L82
- Это уже RangeError

**Comment by Maksym04** [comment]
Исправил

**Comment by shevictory** [comment]
Это не только тут

**Comment by pecourses** [comment]
Это не только тут

**Comment by Maksym04** [comment]
Да, увидел, в одном месте пропустил исправить
