### ISSUE TITLE
Возвращаемое значение

### ISSUE THREAD

**Issue by pecourses** [Maksym04/js.class-syntax#3]
https://github.com/Maksym04/js.class-syntax/blob/4ef3add8aab72c937906913c875dc3b830333069/js/index.js#L96
- Как правило, если метод что-то проверяет, то возвращает истину или ложь, а не выводит сообщение.

**Comment by Maksym04** [comment]
Исправил

**Comment by pecourses** [comment]
Если исправили, можете закрывать ишью
